# permissions for end users to view s3bucketgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: s3bucketgroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: art-of-infrastructure-management
    app.kubernetes.io/part-of: art-of-infrastructure-management
    app.kubernetes.io/managed-by: kustomize
  name: s3bucketgroup-viewer-role
rules:
- apiGroups:
  - bucketgroup.my.domain
  resources:
  - s3bucketgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bucketgroup.my.domain
  resources:
  - s3bucketgroups/status
  verbs:
  - get
